### ISSUE TITLE
RFC - Usage of Store and Store Getters

### ISSUE THREAD

**Issue by bastihav** [upb-uc4/ui-web#170]
# Current state:
Currently, we just use the store as place for our variables, but do not make use of getters, mutations, actions and so on.
Because of this, any time we "fail" to read data from the store, e.g. when we refresh the browser and there is no login data left, we would need to manually, from every component we reach this state in, push new data to the store, i.e. open a login prompt etc.

# Proposed change:
We use getLoginData() instead of directly reading from the variable.

The code could then look something like this (just a sketch):
```
getLoginData() {
    if(!hasLoginData) {
        {success, loginData} = promptLogin()  //maybe a login modal?
        if (success)
            setLoginData(success)
        else 
            // do something else, maybe return empty loginData, like we would do now?
    }

    return loginData;
}  
```

IMO this would still make sense for login, even though we will use authentication tokens in the future, because these will have a expiration time and after that, we would still rely on a re-login.

Similar code for myRole, myId (-> we could just remove this actually, and use the loginData.username)

# Comments
This would also be a good preparation for https://github.com/upb-uc4/api/issues/5 

If we choose to implement that, we would have a getCertificate(), which would basically work in the same way. Otherwise we would require a complete relog even though the authentication token is still there, because we would loose either the encrypted or decrypted certificate or the decryption password from the state (depending on what we store) and not be able to retrieve it without code duplication in all components

@tobias-wiese @theovier

**Comment by tobias-wiese** [comment]
This seems to be a very good idea
