### ISSUE TITLE
JWT, Persistence and CSRF

### ISSUE THREAD

**Issue by bastihav** [upb-uc4/ui-web#186]
# JWT, Persistence and CSRF

As explained in the workshop last week, we want to use JWT for authentication for all our API calls between the frontend (Vue) and backend (Lagom).
In the following, I will try to explain the architecture as I understood it:

## Architecture

We have three major applications:
Vue frontend, Lagom Authentication Server, Lagom Content Servers

In this scenario, the front end can place API calls to the Auth server to get a short-lived authentication JWT and a long-lived refresh JWT. 
Using the refresh JWT, we can ask for new authentication JWT, using the authentication JWT, we can access the other APIs, that can serve content like courses or user data.

## Basic Approach: JWT in Memory Only
When logging into the website for the first time, the server sends us the tokens, which we will store in vuex's state management, which is strictly just in memory and not local storage.
According to OWASP, local storage should be avoided when handling sensitive data or session identifiers.
This seems like the most secure approach, as the only way to leak the tokens would be using XSS, which vue offers great support against, or if we are stupid enough to leak the tokens on the console or something like that.

### Problems
- No persistence between browser sessions, i.e. even with a refresh token which lasts 24 hours, a single browser page refresh will "log out" the user in the frontend.

## Problematic Approach 1: JWT in Local Storage
From https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html#local-storage:
"A single Cross Site Scripting can be used to steal all the data in these objects, so again it's recommended not to store sensitive information in local storage."
"Do not store session identifiers in local storage as the data is always accessible by JavaScript. Cookies can mitigate this risk using the httpOnly flag."

## Problematic Approach 2: JWT in httpOnly Cookie
This seems to be the "recommended" approach if you want to persist JWT between browser sessions.
The JWT is sent by the auth server using an http only cookie, so the cookie is never accessible by any JavaScript code, not even our own.
With every HTTP request to the server, the cookie is sent automatically by the browser.

<b>This approach is vulnerable to CSRF attacks!</b>

If a malicious website puts a manipulated API call of our backend into their page and tricks a user, which has an authentication cookie set in their browser to click on the request, the request will be authenticated.

https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#introduction

The OWASP offers vast information on how to build security against CSRF. I will consider the most prominent approaches and give some of my thoughts on how we could use them.

### Token Based Mitigation
The rough idea is to use CSRF tokens for each HTTP request (can be reusable or one time use only). 

Questions:
- How do we get such a token from the backend server?
    - If we request them with an API call thats authenticated using JWT, is that really safe?
        - Why could an attacker not simply use the same CSRF attack on this API call and receive a valid CSRF token to then use for the "real" attack?
        - How could we get a CSRF token for the very first API call? We use a client-side rendered frontend SPA and have no backend besides the API.
            - Usually you would generate a token when you deliver the html to the client. We can't afaik.
    - If we request them using username + password, we lose the benefits of persisting JWT between browser sessions.

### SameSite Cookie Attribute
Idea: we only send the cookie, if the request to the target site is in a cross-site browsing context.

Problem:
- Our API calls are always cross-site, as the backend is on a different server (SPA with no real backend)

I do not think, that we can use this without completely rethinking our frontend architecture.

### Verifying Origin With Standard Headers
Using the HTTP request headers "source origin", "target origin", the backend determines if the request is sent from the correct applicaton.

Problem:
- vulnerable to XSS

### Double Submit Cookie
Send CSRF in both a cookie and as a HTTP header, useful if the server does not want to maintain state.
Seems like it is the same problem as token based mitigation in general though, how do we get these tokens in the very first place?

**Comment by theovier** [comment]
Thanks for putting this together. 
It seems to be a dilemma since "we use a client-side rendered frontend SPA and have no backend besides the API" to send us a CSRF Token. We should discuss this with @bhermann. 

I will also look into this further.

**Comment by janniclas** [comment]
just to clarify, because I don't really understand this right now. What do you mean u have no real backend serving the vue application? Is this a static site and u hosted in in a cdn? 

What I would expect is something like this (sorry for the bad drawing, I'm on the road and only got my phone and a notebook ):

![proxy-architecture](https://user-images.githubusercontent.com/8062521/87911292-ab271c80-ca6b-11ea-91c4-c5152f55ad08.jpg)

So you would hide all your services behind some proxy, the auth service reachable from yourdomain.com/auth/... your api from yourdomain.com/api/... etc.

**Comment by bastihav** [comment]
Yes, that is correct.
We have a nginx that
- proxies /deploy to an docker running nginx, which serves our index.html for our frontend
- provies /api to a traefik node (inside the minikube which hosts lagom), that serves lagom services

The problem here is, that we only serve our index.html (and javascript files), but as we serve a single page application, we (correct me if I am wrong) do not have any way to "inject" a CSRF token into one of our forms, as the DOM is always rendered/generated clientside.

So we could only inject a CSRF token directly into the index.html, at which point the user is not authenticated, so I am not sure if this would bring any protection against CSRF.

Maybe I am missing something here, but that is how I understood it.

**Comment by janniclas** [comment]
you are right with the csrf token I think. I was just thinking about your explanation about the samesite attribute. That got me confused, because if you proxy every service behind the same domain you could ues the samesite attribute if I'm not mistaken?

**Comment by bastihav** [comment]
You are right, that should work.

The only downside to this is, that we restrict our architecture with this approach, i.e. the server, that serves our frontend, always needs to host or proxy the API, but I guess that is okay.

So our approach would be
- On first login, lagom sends us a http-only, sameSite, secure cookie containing the authentication token and a similar cookie containing the refresh token (or send the authentication token only in the http body)

- On page reload, we try to authenticate using the authentication token in our store/cookie, if it fails we try to get a new authentication token using our refresh token, if that fails we prompt the user to enter their login data again.


We would not need / could not provide CSRF mitigation for the first login, but users that enter their login data on a different domain would probably find other ways to break the security too.

**Comment by janniclas** [comment]
Sounds good to me. 
Let‘s see if @bhermann wants to enlighten us any further, but for me this would be a Good and practical way to start.

**Comment by bhermann** [comment]
I agree. The proposed solution looks feasible in the current architecture and provides a good security. Attacks to this would be very hard and also pretty specialized (i.e. unlikely, but possible).

The alternative I had in mind would have either involve that the website would be served by the same webserver as the authentication service (ugh wrt the current architecture) or some hacky internal token sharing with the two involved webservers using ModSecurity's injection capabilities on the nginx. All pretty weird. 

We didn't run into this with Delphi because we deliver the website through Scala Play and can therefore easily inject a token during the initial render.
