### ISSUE TITLE
Refactor all v-models in combination with emits

### ISSUE THREAD

**Issue by tobias-wiese** [upb-uc4/ui-web#235]
Until now, we mostly use ```emit``` for updating the v-model of a parent component. We should use the new modelWrapper of Vue3
Can be implemented in combination with #244

**Comment by theovier** [comment]
Just to clarify we are talking about the use of [`/use/ModelWrapper`](https://github.com/upb-uc4/ui-web/blob/develop/src/use/ModelWrapper.ts).
