### ISSUE TITLE
Selecting a value in the dropdowns for birthday always take two attempts

### ISSUE THREAD

**Issue by bhermann** [upb-uc4/ui-web#257]
**Describe the bug**
When selecting a date, a month, or a year for a birthdate, I always need two attempts. At first I thought it was me, but I made a recording, where you can clearly see the effect. 

**To Reproduce**
1. Go to 'Create user' form
2. Click on the date dropdown...
3. Select a date.

**Expected behavior**
Value should be selected on the first attempt. 

**Screenshots**
![screen recording birthdate uc4_2](https://user-images.githubusercontent.com/1974799/88913197-c0b4f700-d260-11ea-9b1e-950a68abfff6.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 84

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by bastihav** [comment]
I can not reproduce this on Chrome 84 or Firefox 77 on windows. @theovier can you test if this is a MacOS problem? :P

**Comment by tobias-wiese** [comment]
I could not reproduce this error on windows, too.

**Comment by bhermann** [comment]
By the way: I made a bad cut with the screen recording. I have the error for the date field as well. The video just starts at the second attempt.

**Comment by theovier** [comment]
I can reproduce this bug using Chrome 79 on MacOS. I will update my Chrome version soon and report back.
