### ISSUE TITLE
Make real name easily accessible from course object

### ISSUE THREAD

**Issue by tobias-wiese** [upb-uc4/ui-web#349]
- atm it is just possible to search for a lecturer by its username. Getting the full name for each course just for filtering would introduce a significant overhead.

**2 Options:**
1. save the full name, that we get via the API calls FOR EACH course in the course object
2. get the lecturer name included in the course object, that we get from the API

**Comment by bastihav** [comment]
We do not want to persist the same information in two places, so the primary key (lecturer username) is the only reference in the course database. If we would add the full name of the lecturer in the course, but not in the database, lagom would have to
- query the user database for each getCourse (-> this is against their concept, I think)
- add the lecturerName to persisted information inside the course database (-> on user update, need to query and update all courses, again, this is a cross service job which is undesirable)

I agree, that a "get courses by lecturer full name" would be a nice feature,
For now, while we do not have any pagination, we can use the "getAllCourses" + "getUsersByUsernames" (so two queries in total). This approach will not work when we want to filter server side (+ pagination).

@dhelmert

**Comment by dhelmert** [comment]
I agree, that having the same information in two places is bad practice.
I would say we create a new endpoint in the user service, to find lecturerIds, given the names of lecturers. Then, having the lecturerIds, you can send a request "getAllCourses" with lecturerIds as query parameter.
This splits the request into two, but avoids redundant information storing, and reduces communication between our seperated services.
