### ISSUE TITLE
Remove "(optional)" behind phone number in account form

### ISSUE THREAD

**Issue by tobias-wiese** [upb-uc4/ui-web#420]
The phone number is not optional atm, but it should be?

**Comment by tobias-wiese** [comment]
It is removed on develop, but anyway we should discuss this

**Comment by theovier** [comment]
I'm not too sure if it should be optional as we've seen that the UPB requires students to add their phone number into Paul during the beginning of corona.

**Comment by tobias-wiese** [comment]
We will leave it as it is, as it is not that relevant for the implementation of our prototype.
