### ISSUE TITLE
Machine User Authentication

### ISSUE THREAD

**Issue by bastihav** [upb-uc4/ui-web#446]
# Problem
Currently, machine users have no easy means to authenticate and use the API.  
All authentication is strictly cookie bound, which makes it cumbersome (or perhaps impossible in some frameworks) to use any of our API endpoints.  
While cookies are, as discussed, the safest implementation of our authentication approach, we still need a way for machine users (e.g. a synchronization or import/export system from/to PAUL or similar applications, or even our unit tests in the frontend) to authenticate and use our API.

# Proposed solution
Similar to our current authentication, we also provide endpoints to get a `refresh` or `login` (access) token. We can then use these tokens in the authentication (bearer) header of every API call, to authenticate them.  
We should make clear, that this authentication is only to be used for machine users that do not use a browser.

# Future
Tokens are currently not saved in the backend and thus, can not be invalidated. This means that I could theoretically use an token even after the password of a user was changed, which should be reworked.  
If we add invalidation of tokens, we could also add the option to create tokens with infinite lifespan, maybe even safe specific permissions for tokens, i.e. let me create a "machine user" token that can create users but not delete them.

**Comment by ldklenner** [comment]
The proposed solution sounds feasible. For every authenticated servicecall we would check if a bearer token or a access cookie is provided. Token and cookie would have the same structure, but we should add a entry which specifies the type of the token.

### Future
The only method I can imagine to support invalidation is to store the token in a database. Using the database as an allow / deny list. Every authenticated servicecall would than need to request the database. Caching seems extremely difficult. If we use a deny list all valid calls (majority) will revert to the database as there would be no entry in the cache. If we use a allow list, we have to make sure that caches and database are synchronized. If a token gets prematurely removed from the database we also have to make sure to remove it from each cache of every service instance, which I am not sure we can implement.

To equip tokens with specific permissions sounds interesting, to some degree we are already able to do that as JWT tokens allow to specify custom payload.

**Comment by bastihav** [comment]
> ### Future
> The only method I can imagine to support invalidation is to store the token in a database. Using the database as an allow / deny list. Every authenticated servicecall would than need to request the database. Caching seems extremely difficult. If we use a deny list all valid calls (majority) will revert to the database as there would be no entry in the cache. If we use a allow list, we have to make sure that caches and database are synchronized. If a token gets prematurely removed from the database we also have to make sure to remove it from each cache of every service instance, which I am not sure we can implement.

Another option would be to only safe tokens in RAM, which of course means that tokens are invalidated if the backend restarts. I think that would be ok, but I am not sure if/how you can synchronize those data structures with multiple (nodes? pods?) instances of the service.
