### ISSUE TITLE
As a user, I want to see a proper mobile representation of the application

### ISSUE THREAD

**Issue by tobias-wiese** [upb-uc4/ui-web#455]

**Comment by theovier** [comment]
Already implemented for mobile usage

## Common

- [ ] Login Page
- [ ] Welcome Page
- [ ] About Page
- [ ] Private Profile
- [ ] Settings Page

## Admin

- [ ] Account List
- [ ] Account Create
- [ ] Account Edit
- [ ] Course List
- [ ] Course Create
- [ ] Course Edit

## Lecturer

- [ ] Course List
- [ ] Course Create
- [ ] Course Edit

## Student

- [ ] Course List
