### ISSUE TITLE
Buttons of mobile navbar are smaller than "clickable" area

### ISSUE THREAD

**Issue by tobias-wiese** [upb-uc4/ui-web#480]
![grafik](https://user-images.githubusercontent.com/63233799/93218528-9ebcf880-f76a-11ea-96b1-b7b13088fbb8.png)

**Comment by theovier** [comment]
lol not again... 
I'll look into this, however, I don't think this is much of an issue as this does not occur on real mobile devices (since you got no hover-style there).

**Comment by tobias-wiese** [comment]
> 
> 
> lol not again...
> I'll look into this, however, I don't think this is much of an issue as this does not occur on real mobile devices (since you got no hover-style there).

I'm sorry :( I tagged it with low prio, just stumbled over it randomly when adding the logo

**Comment by bastihav** [comment]
I disagree. This is indead a problem. You HAVE to click on the text for anything to happen. If you click on the whole width of the element (which I think is very reasonable, if the text is left aligned and my thumb has difficulties reaching the text, but not reaching the whole button width), you even see the hover styling but nothing happens.

![2020-09-18 11 42 22](https://user-images.githubusercontent.com/8998495/93583589-5ab53800-f9a4-11ea-9b13-9c1a5a539423.jpg)

**Comment by theovier** [comment]
> I disagree. This is indead a problem. You HAVE to click on the text for anything to happen. If you click on the whole width of the element (which I think is very reasonable, if the text is left aligned and my thumb has difficulties reaching the text, but not reaching the whole button width), you even see the hover styling but nothing happens.
>

That is simply NOT true on real mobile devices (at least on the ones I own). Clicking inside the div and not on the text is sufficient to trigger the navigation.

**Comment by bastihav** [comment]
I tried it with a local jwt branch build. You are right, it works on the deployed version. We should check again, when jwt is merged.
