### ISSUE TITLE
Replace profile picture placeholder in account list

### ISSUE THREAD

**Issue by tobias-wiese** [upb-uc4/ui-web#518]
- use the profile picture API (maybe in onBeforeMounted() hook)

**Comment by tobias-wiese** [comment]
As we do not want to process the images on lagom side atm, it would not be feasible to load a preview image for each user. Hence, we can remove it from the account list

**Comment by theovier** [comment]
> As we do not want to process the images on lagom side atm, it would not be feasible to load a preview image for each user. Hence, we can remove it from the account list

Is this just temporarily or are we ditching the profile pictures in the list completely? What do you mean with "process the images", could you elaborate? Thanks!

**Comment by tobias-wiese** [comment]
> 
> 
> > As we do not want to process the images on lagom side atm, it would not be feasible to load a preview image for each user. Hence, we can remove it from the account list
> 
> Is this just temporarily or are we ditching the profile pictures in the list completely? What do you mean with "process the images", could you elaborate? Thanks!

Lagom saves the original images, hence each file has up 6mb or so. Loading them for each user for a "preview" image would introduce heavy network load. Somebody said, that processing the images on the server (e.g. lower resolution for preview images) is bad practice. So, we can remove them for the moment. A possible way would be to upload a profile picture AND a preview image frontendside, but that is not part of the current design. We wanted to discuss again, why processing the image on the server should not happen.

**Comment by theovier** [comment]
Alright, thanks for the explanation. I guess that makes sense.
