### ISSUE TITLE
Website not working correctly with uc4.cs.upb.de (authentication fault)

### ISSUE THREAD

**Issue by NikoBergemann** [upb-uc4/ui-web#524]
**Describe the bug**
When accessing our deployment via uc4.cs.upb.de/deploy and trying to log in, you get Authentication Errors.
This is quite possibly the result of some setting in the webservers nginx-config.

**To Reproduce**
1. visit uc4.cs.upb.de/deploy
2. try to log in (e.g. with admin/admin)

**Expected behavior**
The Log in works and you get redirected to your welcome page

**Additional context**
1. Solution: accept the uc4.cs.upb.de certificates as well (currently we only store an ssl cert for uni-paderborn)
2. Solution: redirect all users from uc4.cs.upb.de to uc4.cs.uni.paderborn.de (always), this way we always use the right certificate.

**Comment by bastihav** [comment]
This has nothing to do with our ssl certificates, but is actually a problem with our cookies or rather a security feature.

Cookies are only sent in same-site context, i.e. when I have cookies for uc4.cs.uni-paderborn.de, I only send them with connections to this exact domain. 

We currently always use uc4.cs.uni-paderborn.de as our API endpoints, so if you try to authenticate on uc4.cs.upb.de/deploy, you receive authentication cookies for uc4.cs.upb.de, which will then not be included to actually authenticate requests.

## Solution: 
We could try to redirect from uc4.cs.upb.de to uc4.cs.uni-paderborn.de, as you mentioned.

Alternatively, we could try to change the api endpoint dynamically, depending on the browser URL, but I am not sure if this is considered safe to do.

**Comment by bastihav** [comment]
finally fixed

**Comment by tobias-wiese** [comment]
We had to disable the forwarding again, as the end to end tests ran into an authentication loop. This is most probably a problem with the nginx configuration that is used within the frontend's test pipeline.

**Comment by tobias-wiese** [comment]
This was cause by our nginx configuration used for the test pipeline. Fixed in #753
