### ISSUE TITLE
Courses menu layouted weirdly

### ISSUE THREAD

**Issue by bhermann** [upb-uc4/ui-web#534]
**Versions (Do not change)**
- Frontend: v0.8.1
- Authentication Management: v0.8.2
- Course Management: v0.8.2
- User Management: v0.8.3
- Matriculation Management: v0.8.4

**Describe the bug**
When I log in as `admin` I see a weird layout in the courses submenu.

**To Reproduce**
1. Login as Admin
2. Hover over Courses

**Expected behavior**
A much nicer layout.

**Screenshots**
<img width="232" alt="Screenshot 2020-09-28 at 11 22 40" src="https://user-images.githubusercontent.com/1974799/94414868-22201600-017d-11eb-8345-889109d055c5.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 85.0.4183.102 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by tobias-wiese** [comment]
This bug is already fixed, but not yet deployed. It will be released with ```v.0.9.0```
