### ISSUE TITLE
Can not open navbar links in new tab

### ISSUE THREAD

**Issue by theovier** [upb-uc4/ui-web#553]
It is not possible anymore to open navbar menus in a new tab with the use of the context menu (rightclick -> open in new tab). I reckon the problem is that we don't actually use `router-links` anymore (which are translated into hrefs). It's not really a big deal but a convenient function. However, I don't see a simple solution just now as we purposely decided against `router-links` in favour of `@click` listeners.

**Comment by bastihav** [comment]
We could alternatively go back to router links and handle the async API call like this: 
https://stackoverflow.com/questions/59603149/make-html-a-tag-href-wait-for-async-function-in-onclick-to-return

**Comment by tobias-wiese** [comment]
I do not think, that this is a proper solution for us, because using an ```@click =doSth``` within the ```router-link```- tag cause the application not to route to a new component view, but to a new page. Hence, the whole application is refreshed at that point.

**Comment by bastihav** [comment]
we would obviously need to use router.go or router.push instead of location.href
