### ISSUE TITLE
Missing ETCS field

### ISSUE THREAD

**Issue by david-buderus** [upb-uc4/ui-web#737]
**Versions (Do not change)**
- Frontend: v0.13.0
- Authentication Management: v0.12.0
- Course Management: v0.12.2
- User Management: v0.12.0
- Matriculation Management: v0.12.1
- Certificate Management: v0.12.0
- Examination Regulations Management: v0.12.3

**Describe the bug**
There is no etc field in the course creation of the admin.

**To Reproduce**
1. Login as Admin
2. Open the create a course menu
3. Look at the missing field

**Expected behavior**
There should be an etcs field

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by tobias-wiese** [comment]
This was a design decision, we are aware of. We did not implement the field (for lecturers too), as we planned to get the ECTS information from the ExReg at some point. This is now obsolete, hence we will add the field
