### ISSUE TITLE
Missing lock file

### ISSUE THREAD

**Issue by janniclas** [upb-uc4/ui-web#85]
This repository does not contain a package-lock.json or yarn-lock file.

As stated in the [ npm documentation ](https://docs.npmjs.com/configuring-npm/package-lock-json.html): 
"This file is intended to be committed into source repositories, and serves various purposes: .... " 

Therefore, I would suggest you add this to the repository, if you don't have a specific reason for not committing them.

**Comment by bastihav** [comment]
+1 from me

**Comment by tobias-wiese** [comment]
I removed the package-lock.json from the gitignore and pushed it on develop. It will be available on the master branch after the end of this sprint.
